name: Primer workflow

on: push

permissions:
  security-events: write
  
jobs: 
  hola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Probar codigo
        run: python3 main.py
      - name: Run Pylint analysis
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
